export const productListData = [
  {
    name: 'Crispy Veggie Burger',
    price: 9.85,
    weight: 1,
    measuringUnit: 'Qty',
    isSelected: false,
    quantity: 1,
    sku: 'burger',
    brand: 'Foodie',
    stock: 50,
    description: 'Delicious crispy veggie burger.',
    category: 'Food',
  },
  {
    name: 'Coca Cola',
    price: 7.85,
    weight: 1,
    measuringUnit: 'Ltr',
    isSelected: false,
    quantity: 1,
    sku: 'coca-cola',
    brand: 'Coca Cola',
    stock: 100,
    description: 'Refreshing soft drink.',
    category: 'Beverages',
  },
  {
    name: 'Banana',
    price: 20.0,
    weight: 1,
    measuringUnit: 'Kg',
    isSelected: false,
    quantity: 1,
    sku: 'banana',
    brand: 'Organic',
    stock: 30,
    description: 'Fresh organic bananas.',
    category: 'Produce',
  },
  {
    name: 'Heineken',
    price: 50.22,
    weight: 500,
    measuringUnit: 'ml',
    isSelected: false,
    quantity: 1,
    sku: 'heineken',
    brand: 'Heineken',
    stock: 40,
    description: 'Premium quality beer.',
    category: 'Beverages',
  },
  {
    name: 'Chocolate Cookies',
    price: 9.85,
    weight: 500,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'chocolate-cookies',
    brand: 'Choco Delights',
    stock: 20,
    description: 'Tasty chocolate-flavored cookies.',
    category: 'Food',
  },
  {
    name: 'Potato',
    price: 9.85,
    weight: 1,
    measuringUnit: 'Kg',
    isSelected: false,
    quantity: 1,
    sku: 'potato',
    brand: 'Farm Fresh',
    stock: 60,
    description: 'Organic farm-grown potatoes.',
    category: 'Produce',
  },
  {
    name: 'Bread',
    price: 9.85,
    weight: 400,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'bread',
    brand: 'Bakery Fresh',
    stock: 25,
    description: 'Freshly baked bread.',
    category: 'Food',
  },
  {
    name: 'Cow Milk',
    price: 9.85,
    weight: 1,
    measuringUnit: 'Ltr',
    isSelected: false,
    quantity: 1,
    sku: 'cow-milk',
    brand: 'Dairy Land',
    stock: 80,
    description: 'Pure cow milk.',
    category: 'Dairy',
  },
  {
    name: 'Egg',
    price: 14.0,
    weight: 60,
    measuringUnit: 'Qty',
    isSelected: false,
    quantity: 1,
    sku: 'egg',
    brand: 'Farm Eggs',
    stock: 120,
    description: 'Fresh farm eggs.',
    category: 'Food',
  },
  {
    name: 'Hot Dog',
    price: 9.85,
    weight: 150,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'hot-dog',
    brand: 'Hot Stuff',
    stock: 35,
    description: 'Classic hot dog.',
    category: 'Food',
  },
  {
    name: 'Sausage Buns',
    price: 4.85,
    weight: 200,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'sausage-buns',
    brand: 'Bakery Fresh',
    stock: 30,
    description: 'Fresh sausage buns.',
    category: 'Food',
  },
  {
    name: 'Avocado',
    price: 9.85,
    weight: 200,
    measuringUnit: 'Qty',
    isSelected: false,
    quantity: 1,
    sku: 'avocado',
    brand: 'Organic',
    stock: 45,
    description: 'Ripe avocado.',
    category: 'Produce',
  },
  {
    name: 'Tomato',
    price: 5.85,
    weight: 1,
    measuringUnit: 'Kg',
    isSelected: false,
    quantity: 1,
    sku: 'tomato',
    brand: 'Farm Fresh',
    stock: 70,
    description: 'Fresh tomatoes.',
    category: 'Produce',
  },
  {
    name: 'Chanol Perfume',
    price: 9.85,
    weight: 50,
    measuringUnit: 'ml',
    isSelected: false,
    quantity: 1,
    sku: 'chanol-perfume',
    brand: 'Chanol',
    stock: 15,
    description: 'Luxury perfume.',
    category: 'Beauty',
  },
  {
    name: 'Dove Shampoo',
    price: 7.3,
    weight: 250,
    measuringUnit: 'ml',
    isSelected: false,
    quantity: 1,
    sku: 'dove-shampoo',
    brand: 'Dove',
    stock: 55,
    description: 'Nourishing shampoo.',
    category: 'Personal Care',
  },
  {
    name: 'Cucumber',
    price: 9.85,
    weight: 300,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'cucumber',
    brand: 'Farm Fresh',
    stock: 90,
    description: 'Fresh cucumber.',
    category: 'Produce',
  },
  {
    name: 'Lip Balm',
    price: 9.85,
    weight: 15,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'lip-balm',
    brand: 'Beauty Care',
    stock: 20,
    description: 'Moisturizing lip balm.',
    category: 'Beauty',
  },
  {
    name: 'Cigarette',
    price: 9.85,
    weight: 1,
    measuringUnit: 'Pack',
    isSelected: false,
    quantity: 1,
    sku: 'cigarette',
    brand: 'Tobacco Co',
    stock: 10,
    description: 'Pack of cigarettes.',
    category: 'Other', // Or "Tobacco" if you want a specific category
  },
  {
    name: 'Dior Miss Spice',
    price: 9.85,
    weight: 100,
    measuringUnit: 'ml',
    isSelected: false,
    quantity: 1,
    sku: 'dior-miss-spice',
    brand: 'Dior',
    stock: 12,
    description: 'Elegant perfume.',
    category: 'Beauty',
  },
  {
    name: 'Coffee Beans',
    price: 9.85,
    weight: 250,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'coffee-beans',
    brand: 'Coffee World',
    stock: 40,
    description: 'Fresh coffee beans.',
    category: 'Beverages',
  },
  {
    name: 'Butter',
    price: 9.85,
    weight: 200,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'butter',
    brand: 'Dairy Land',
    stock: 50,
    description: 'Pure butter.',
    category: 'Dairy',
  },
  {
    name: 'Broccoli',
    price: 9.85,
    weight: 500,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'broccoli',
    brand: 'Farm Fresh',
    stock: 60,
    description: 'Fresh broccoli.',
    category: 'Produce',
  },
];
