import {
  Avocado,
  Banana,
  Butter,
  Cigarette,
  CocaCola,
  CoffeBeans,
  CowMilk,
  CrispyVeggieBurger,
  DoveShampoo,
  Eggs,
  Garlic,
  Heineken,
  HotDog,
  IndianMixSpices,
  LipBalm,
  Mayonnaise,
  Potato,
  Tomato,
} from './assets';
import product1 from './assets/react.svg';

export const productListData = [
  {
    name: 'Crispy Veggie Burger',
    price: 9.85,
    weight: 1,
    measuringUnit: 'Qty',
    isSelected: false,
    quantity: 1,
    sku: 'burger',
    brand: 'Foodie',
    stock: 50,
    description: 'Delicious crispy veggie burger.',
    category: 'Food',
    image: CrispyVeggieBurger ?? '',
    ebt: true,
  },
  {
    name: 'Coca Cola',
    price: 7.85,
    weight: 1,
    measuringUnit: 'Ltr',
    isSelected: false,
    quantity: 1,
    sku: 'coca-cola',
    brand: 'Coca Cola',
    stock: 100,
    description: 'Refreshing soft drink.',
    category: 'Beverages',
    image: CocaCola ?? '',
    ebt: false,
  },
  {
    name: 'Banana',
    price: 20.0,
    weight: 1,
    measuringUnit: 'Kg',
    isSelected: false,
    quantity: 1,
    sku: 'banana',
    brand: 'Organic',
    stock: 30,
    description: 'Fresh organic bananas.',
    category: 'Produce',
    image: Banana ?? '',
    ebt: true,
  },
  {
    name: 'Whiskey',
    price: 59.99,
    weight: 750,
    measuringUnit: 'ml',
    isSelected: false,
    quantity: 1,
    sku: 'whiskey',
    brand: 'Jack Daniels',
    stock: 25,
    description: 'Aged whiskey for premium taste.',
    category: 'Alcohol',
    image: Heineken ?? '',
    ebt: false,
  },
  {
    name: 'Wine',
    price: 45.99,
    weight: 750,
    measuringUnit: 'ml',
    isSelected: false,
    quantity: 1,
    sku: 'wine',
    brand: 'Château Vin',
    stock: 30,
    description: 'Classic red wine.',
    category: 'Alcohol',
    image: Heineken ?? '',
    ebt: false,
  },
  {
    name: 'Beer',
    price: 12.99,
    weight: 500,
    measuringUnit: 'ml',
    isSelected: false,
    quantity: 1,
    sku: 'beer',
    brand: 'Local Brewery',
    stock: 60,
    description: 'Refreshing craft beer.',
    category: 'Alcohol',
    image: Heineken ?? '',
    ebt: false,
  },
  {
    name: 'Cigarette',
    price: 9.85,
    weight: 1,
    measuringUnit: 'Pack',
    isSelected: false,
    quantity: 1,
    sku: 'cigarette',
    brand: 'Tobacco Co',
    stock: 10,
    description: 'Pack of cigarettes.',
    category: 'Tobacco',
    image: Cigarette ?? '',
    ebt: false,
  },
  {
    name: 'Butter',
    price: 9.85,
    weight: 200,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'butter',
    brand: 'Dairy Land',
    stock: 50,
    description: 'Pure butter.',
    category: 'Dairy',
    image: Butter ?? '',
    ebt: true,
  },
  {
    name: 'Avocado',
    price: 9.85,
    weight: 1.5,
    measuringUnit: 'Kg',
    isSelected: false,
    quantity: 1,
    sku: 'avocado',
    brand: 'Organic Farm',
    stock: 20,
    description: 'Fresh and creamy avocados.',
    category: 'Produce',
    image: Avocado ?? '',
    ebt: true,
  },
  {
    name: 'Tomato',
    price: 9.85,
    weight: 0.5,
    measuringUnit: 'Kg',
    isSelected: false,
    quantity: 1,
    sku: 'tomato',
    brand: 'Organic Farm',
    stock: 40,
    description: 'Ripe and juicy tomatoes.',
    category: 'Produce',
    image: Tomato ?? '',
    ebt: true,
  },
  {
    name: 'Potato',
    price: 9.85,
    weight: 1,
    measuringUnit: 'Kg',
    isSelected: false,
    quantity: 1,
    sku: 'potato',
    brand: 'Organic Farm',
    stock: 50,
    description: 'Fresh and starchy potatoes.',
    category: 'Produce',
    image: Potato ?? '',
    ebt: true,
  },
  {
    name: 'Garlic',
    price: 9.85,
    weight: 0.1,
    measuringUnit: 'Kg',
    isSelected: false,
    quantity: 1,
    sku: 'garlic',
    brand: 'Organic Farm',
    stock: 50,
    description: 'Aromatic fresh garlic.',
    category: 'Produce',
    image: Garlic ?? '',
    ebt: true,
  },
  {
    name: 'Dove Shampoo',
    price: 7.3,
    weight: 500,
    measuringUnit: 'ml',
    isSelected: false,
    quantity: 1,
    sku: 'dove-shampoo',
    brand: 'Dove',
    stock: 50,
    description: 'Nourishing shampoo for healthy hair.',
    category: 'Personal Care',
    image: DoveShampoo ?? '',
    ebt: false,
  },
  {
    name: 'Mayonnaise',
    price: 9.85,
    weight: 200,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'mayonnaise',
    brand: 'Creamy',
    stock: 40,
    description: 'Smooth and creamy mayonnaise.',
    category: 'Dairy',
    image: Mayonnaise ?? '',
    ebt: true,
  },
  {
    name: 'Coffee Beans',
    price: 9.85,
    weight: 500,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'coffee-beans',
    brand: 'WakeUp',
    stock: 25,
    description: 'Rich and aromatic coffee beans.',
    category: 'Beverages',
    image: CoffeBeans ?? '',
    ebt: false,
  },
  {
    name: 'Cow Milk',
    price: 9.85,
    weight: 1,
    measuringUnit: 'Ltr',
    isSelected: false,
    quantity: 1,
    sku: 'milk',
    brand: 'Dairy Land',
    stock: 80,
    description: 'Pure cow milk.',
    category: 'Dairy',
    image: CowMilk ?? '',
    ebt: true,
  },
  {
    name: 'Egg',
    price: 14.0,
    weight: 60,
    measuringUnit: 'Qty',
    isSelected: false,
    quantity: 1,
    sku: 'egg',
    brand: 'Farm Eggs',
    stock: 120,
    description: 'Fresh farm eggs.',
    category: 'Food',
    image: Eggs ?? '',
    ebt: true,
  },
  {
    name: 'Indian Mix Spices',
    price: 9.85,
    weight: 200,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'indian-mix-spices',
    brand: 'Spice House',
    stock: 30,
    description: 'Aromatic mix of Indian spices.',
    category: 'Food',
    image: IndianMixSpices ?? '',
    ebt: true,
  },
  {
    name: 'Hot Dog',
    price: 9.85,
    weight: 200,
    measuringUnit: 'gm',
    isSelected: false,
    quantity: 1,
    sku: 'hot-dog',
    brand: 'Food',
    stock: 30,
    description: 'Aromatic mix of hot dog.',
    category: 'Food',
    image: HotDog ?? '',
    ebt: true,
  },
  {
    name: 'Lip Balm',
    price: 9.85,
    weight: 1,
    measuringUnit: 'Qty',
    isSelected: false,
    quantity: 1,
    sku: 'lip-balm',
    brand: 'Vaseline',
    stock: 35,
    description: 'Moisturizing lip balm for soft lips.',
    category: 'Personal Care',
    image: LipBalm ?? '',
    ebt: false,
  },
  {
    name: 'Apple',
    price: 15.0,
    weight: 1,
    measuringUnit: 'Kg',
    isSelected: false,
    quantity: 1,
    sku: 'apple',
    brand: 'Organic',
    stock: 40,
    description: 'Fresh organic apples.',
    category: 'Produce',
    image: product1 ?? '',
    ebt: true,
  },
  {
    name: 'Carrots',
    price: 10.5,
    weight: 1,
    measuringUnit: 'Kg',
    isSelected: false,
    quantity: 1,
    sku: 'carrots',
    brand: 'Farm Fresh',
    stock: 50,
    description: 'Crisp and fresh carrots.',
    category: 'Produce',
    image: product1 ?? '',
    ebt: true,
  },
];
